name: package-getting-started-app
on : [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree

      - uses: docker/setup-buildx-action@v1

      - name: Login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: AllanBl22/getting-started-app:latest

      
        
# Checkout le code
# Build image
# push sur dockerhub
