name: package-getting-started-app
on : [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree

      - uses: docker/setup-buildx-action@v1

      - name: Login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to your Dockerfile and other necessary files
          file: ./path/to/Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
            my-dockerhub-username/my-repo-name:latest
            my-dockerhub-username/my-repo-name:${{ github.sha }}

      
        
# Checkout le code
# Build image
# push sur dockerhub
