name : package-getting-started-app
on : [push]
jobs:
  package-getting-started-app:
    run-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo "This step will be skipped on Monday and Wednesday"
    # Checkout le code
    # Build image
    # push sur dockerhub
