name : package-getting-started-app
on : [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
      - uses: actions/checkout@v2
        
    # Checkout le code
    # Build image
    # push sur dockerhub
